### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by MarcusDDS1609** [jaketr00/Discord-Bot-Client#7]
`Error: Cannot find module './FormData'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/Users/nadiamiah/Desktop/Bots/Discord-Bot-Client/node_modules/electron/di
st/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nadiamiah/Desktop/Bots/Discord-Bot-Client/node_modules/snekfetch/src/node/index.
js:6:18)
    at Object.<anonymous> (/Users/nadiamiah/Desktop/Bots/Discord-Bot-Client/node_modules/snekfetch/src/node/index.
js:153:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
`
This didn't happen when I was using an old version of this, however I saw there was another update so I deleted my old folder and downloaded this new one. But I'm getting this error now :/

**Comment by MarcusDDS1609** [comment]
I redownloaded all the node_modules and it started working, sorry xD
